/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_random_track"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/random/two": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_two_random_tracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracks/{track_id}/album-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_album_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlbumImageResponse: {
            album_image_url?: string | null;
            track_id: string;
        };
        TrackInfo: {
            album_image_url?: string | null;
            artist: string;
            artist_id: string;
            /** Format: int64 */
            ms_duration: number;
            /** Format: int64 */
            ms_played: number;
            /** Format: int32 */
            popularity: number;
            preview_url?: string | null;
            spotify_url?: string | null;
            time_distribution: number[];
            /** Format: int32 */
            times_played: number;
            title: string;
        };
        TwoTracksResponse: {
            track1: components["schemas"]["TrackInfo"];
            track2: components["schemas"]["TrackInfo"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_random_track: {
        parameters: {
            query?: {
                /** @description The user whose data to query */
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackInfo"];
                };
            };
        };
    };
    get_two_random_tracks: {
        parameters: {
            query?: {
                /** @description The user whose data to query */
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Two random tracks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoTracksResponse"];
                };
            };
        };
    };
    get_album_image: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spotify track ID */
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album image URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumImageResponse"];
                };
            };
        };
    };
}
